[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sdm_eurec4a"
version = "0.2.0"
author = "Nils Niebaum"
authors = [{name = "Nils Niebaum", email = "nils.niebaum@gmx.de"},{name = "Clara Bayley", email = "yoctoyotta1024@yahoo.com"}]
description = "Use Super-Droplet Model and EUREC4A data to simulate rain evaporation"
readme = "README.md"
license = "GPL-3.0-or-later"
classifiers = ["Private :: Do Not Upload",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Development Status :: 2 - Pre-Alpha",]
# dynamic = ["version", "description"]
homepage = "https://github.com/yoctoyotta1024/sdm-eurec4a"
issues = "https://github.com/yoctoyotta1024/sdm-eurec4a/issues"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pip>=23.3.2",
    "pytest>=7.4.4",
    "numpy>=1.26.3",
    "scipy>=1.11.4",
    "pandas>=2.1.4",
    "lmfit>=1.2.2",
    "matplotlib>=3.8.2",
    "cftime>=1.6.3",
    "cartopy>=0.22.0",
    "click>=8.1.7",
    "pre-commit>=3.6.0",
    "bottleneck>=1.3.5",
    "netcdf4>=1.6.5",
    "dask>=2023.12.1",
    "xarray>=2023.12.0",
    "pyshp>=2.3.1",
    "ipykernel>=7.3.0",
    "tqdm>=4.68.4",
    "dask_jobqueue>=0.9.0",
    "awkward>=2.10.0",
    "mpi4py>=4.1.2",
    "ruamel-yaml>=0.19.1",
    "seaborn>=0.13.2",
    "zarr>=3.3.0",
]


[project.urls]
homepage = "https://github.com/yoctoyotta1024/sdm-eurec4a"
issues = "https://github.com/yoctoyotta1024/sdm-eurec4a/issues"


[project.optional-dependencies]
test = ["black>=21.9b0",
    "pytest-cov==3.0.0",]

deploy = ["flit==3.4.0",]

[tool.interrogate]
# tool to check code documentation
# https://interrogate.readthedocs.io/en/latest/
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = true
ignore-private = true
ignore-property-decorators = true
ignore-module = false
fail-under = 90
exclude = ["setup.py", "docs", "tests", "data", "notebooks", "temporary"]
verbose = 1
quiet = false
color = true

[tool.isort]
known_third_party = ["click", "pytest", "sdm_eurec4a"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
# only test the root level, otherwise it picks up the tests of the project template
testpaths = ["tests",]

[tool.black]
line-length = 105
target-version = ['py311']

[tool.docformatter]
black = true
in-place = true
pre-summary-newline = true

# [tool.flake8]
# max-line-length = 105
# extend-ignore = "E203, W503, E501, E712, F401"
# select = ["C", "E", "F", "W", "B", "B950"]

[tool.codespell]
skip = "*.nc,*.ipynb,./notebooks/*,environment.yml"
quiet-level = 2
builtin = "clear,rare,code"
ignore-words-list = "jupyter,Jupyter"
write-changes = true
